In [1]:
import pandas as pd
import numpy as np

In [52]:
path = 'C:/Users/bearp/Documents/Forex_DB/'

In [ ]:
Year = ['2011','2012','2013','2014','2015','2016','2017','2018','2019']
file_list = []
for i in Year:
    file_list.append('df_'+i)
print(file_list)

y = 0
for i in file_list:
    yr = Year[y]
    globals()[i]=pd.read_excel(path+'Annualof_'+yr+'.xls')
    y = y+1

['df_2011', 'df_2012', 'df_2013', 'df_2014', 'df_2015', 'df_2016', 'df_2017', 'df_2018', 'df_2019']

In [43]:
df_2014.head()

,Market_and_Exchange_Names,As_of_Date_In_Form_YYMMDD,Report_Date_as_MM_DD_YYYY,CFTC_Contract_Market_Code,CFTC_Market_Code,CFTC_Region_Code,CFTC_Commodity_Code,Open_Interest_All,NonComm_Positions_Long_All,NonComm_Positions_Short_All,...,Conc_Net_LE_8_TDR_Short_Old,Conc_Gross_LE_4_TDR_Long_Other,Conc_Gross_LE_4_TDR_Short_Other,Conc_Gross_LE_8_TDR_Long_Other,Conc_Gross_LE_8_TDR_Short_Other,Conc_Net_LE_4_TDR_Long_Other,Conc_Net_LE_4_TDR_Short_Other,Conc_Net_LE_8_TDR_Long_Other,Conc_Net_LE_8_TDR_Short_Other,Contract_Units
0,WHEAT-SRW - CHICAGO BOARD OF TRADE,141230,2014-12-30,001602,CBT,0,1,472346,130083,107035,...,21.1,21.9,17.5,34.8,28.7,20.2,16.0,29.2,24.3,"(CONTRACTS OF 5,000 BUSHELS)"
1,WHEAT-SRW - CHICAGO BOARD OF TRADE,141223,2014-12-23,001602,CBT,0,1,509223,134414,107467,...,19.7,21.6,17.5,34.1,28.5,20.4,16.2,29.7,24.7,"(CONTRACTS OF 5,000 BUSHELS)"
2,WHEAT-SRW - CHICAGO BOARD OF TRADE,141216,2014-12-16,001602,CBT,0,1,491303,126198,105233,...,21.1,24.4,19.0,38.1,31.7,24.0,16.8,34.1,27.3,"(CONTRACTS OF 5,000 BUSHELS)"
3,WHEAT-SRW - CHICAGO BOARD OF TRADE,141209,2014-12-09,001602,CBT,0,1,464881,121164,113486,...,21.9,26.0,18.8,37.5,30.8,25.7,17.2,35.7,26.9,"(CONTRACTS OF 5,000 BUSHELS)"
4,WHEAT-SRW - CHICAGO BOARD OF TRADE,141202,2014-12-02,001602,CBT,0,1,461562,112393,118333,...,20.5,27.4,18.2,40.3,30.7,27.3,16.6,38.8,26.5,"(CONTRACTS OF 5,000 BUSHELS)"

In [44]:
df=pd.DataFrame()
for i in file_list:
    df = df.append(globals()[i], ignore_index=True)
    print(df.shape)

(7659, 126)
(15677, 126)
(26260, 126)
(38842, 126)
(50940, 126)
(63764, 126)
(76525, 126)
(90295, 126)
(104051, 126)

In [49]:
df_a = df.loc[:,:'NonRept_Positions_Short_Other']

In [45]:
USD_index = df[df['Market_and_Exchange_Names'] == 'U.S. DOLLAR INDEX - ICE FUTURES U.S.']

In [46]:
# Put the Date as Index
USD_index['Date']=USD_index.loc[:,'Report_Date_as_MM_DD_YYYY'].copy()
USD_index=USD_index.set_index('Date').sort_index(ascending=True)
USD_index.head()

C:\Users\bearp\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Market_and_Exchange_Names,As_of_Date_In_Form_YYMMDD,Report_Date_as_MM_DD_YYYY,CFTC_Contract_Market_Code,CFTC_Market_Code,CFTC_Region_Code,CFTC_Commodity_Code,Open_Interest_All,NonComm_Positions_Long_All,NonComm_Positions_Short_All,...,Conc_Net_LE_8_TDR_Short_Old,Conc_Gross_LE_4_TDR_Long_Other,Conc_Gross_LE_4_TDR_Short_Other,Conc_Gross_LE_8_TDR_Long_Other,Conc_Gross_LE_8_TDR_Short_Other,Conc_Net_LE_4_TDR_Long_Other,Conc_Net_LE_4_TDR_Short_Other,Conc_Net_LE_8_TDR_Long_Other,Conc_Net_LE_8_TDR_Short_Other,Contract_Units
Date,,,,,,,,,,,,,,,,,,,,,
2011-01-04,U.S. DOLLAR INDEX - ICE FUTURES U.S.,110104,2011-01-04,098662,ICUS,1,98,28106,18598,19870,...,64.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,(U.S. DOLLAR INDEX X $1000)
2011-01-11,U.S. DOLLAR INDEX - ICE FUTURES U.S.,110111,2011-01-11,098662,ICUS,1,98,36854,23940,13859,...,70.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,(U.S. DOLLAR INDEX X $1000)
2011-01-18,U.S. DOLLAR INDEX - ICE FUTURES U.S.,110118,2011-01-18,098662,ICUS,1,98,33352,20227,14998,...,67.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,(U.S. DOLLAR INDEX X $1000)
2011-01-25,U.S. DOLLAR INDEX - ICE FUTURES U.S.,110125,2011-01-25,098662,ICUS,1,98,39751,24307,22839,...,66.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,(U.S. DOLLAR INDEX X $1000)
2011-02-01,U.S. DOLLAR INDEX - ICE FUTURES U.S.,110201,2011-02-01,098662,ICUS,1,98,42970,26235,29752,...,62.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,(U.S. DOLLAR INDEX X $1000)

In [33]:
df_market = df.groupby('Market_and_Exchange_Names')
df_market.head()

,Market_and_Exchange_Names,As_of_Date_In_Form_YYMMDD,Report_Date_as_MM_DD_YYYY,CFTC_Contract_Market_Code,CFTC_Market_Code,CFTC_Region_Code,CFTC_Commodity_Code,Open_Interest_All,Dealer_Positions_Long_All,Dealer_Positions_Short_All,...,Conc_Gross_LE_4_TDR_Short_All,Conc_Gross_LE_8_TDR_Long_All,Conc_Gross_LE_8_TDR_Short_All,Conc_Net_LE_4_TDR_Long_All,Conc_Net_LE_4_TDR_Short_All,Conc_Net_LE_8_TDR_Long_All,Conc_Net_LE_8_TDR_Short_All,Contract_Units,CFTC_SubGroup_Code,FutOnly_or_Combined
0,CANADIAN DOLLAR - CHICAGO MERCANTILE EXCHANGE,141230,2014-12-30,090741,CME,0,90,113246,18453,1409,...,24.9,41.6,33.5,27.4,23.5,37.7,30.7,"(CONTRACTS OF CAD 100,000)",F10,Combined
1,CANADIAN DOLLAR - CHICAGO MERCANTILE EXCHANGE,141223,2014-12-23,090741,CME,0,90,115355,17739,1494,...,25.5,42.3,34.1,27.6,24.1,38.3,31.0,"(CONTRACTS OF CAD 100,000)",F10,Combined
2,CANADIAN DOLLAR - CHICAGO MERCANTILE EXCHANGE,141216,2014-12-16,090741,CME,0,90,145773,29261,7512,...,31.2,49.2,39.6,26.5,20.9,36.4,27.7,"(CONTRACTS OF CAD 100,000)",F10,Combined
3,CANADIAN DOLLAR - CHICAGO MERCANTILE EXCHANGE,141209,2014-12-09,090741,CME,0,90,122340,29341,6631,...,26.2,45.5,34.8,30.3,25.3,42.8,33.6,"(CONTRACTS OF CAD 100,000)",F10,Combined
4,CANADIAN DOLLAR - CHICAGO MERCANTILE EXCHANGE,141202,2014-12-02,090741,CME,0,90,124383,27540,5685,...,24.7,44.8,34.3,28.1,24.1,40.6,31.2,"(CONTRACTS OF CAD 100,000)",F10,Combined
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12435,5 YEAR ERIS SWAP - CHICAGO BOARD OF TRADE,191217,2019-12-17,344601,CBT,0,344,49133,11499,93,...,79.4,100.0,92.3,30.5,19.4,31.2,27.6,"100,000 USD notional principal",F50,Combined
12436,5 YEAR ERIS SWAP - CHICAGO BOARD OF TRADE,191210,2019-12-10,344601,CBT,0,344,53246,11499,135,...,79.7,99.6,91.9,32.7,26.6,37.9,33.8,"100,000 USD notional principal",F50,Combined
12437,5 YEAR ERIS SWAP - CHICAGO BOARD OF TRADE,191203,2019-12-03,344601,CBT,0,344,50521,11499,0,...,81.5,99.8,93.9,37.2,33.5,42.9,41.3,"100,000 USD notional principal",F50,Combined
12438,5 YEAR ERIS SWAP - CHICAGO BOARD OF TRADE,191126,2019-11-26,344601,CBT,0,344,51196,11499,0,...,81.5,99.8,93.7,36.7,32.9,42.1,39.9,"100,000 USD notional principal",F50,Combined
12439,5 YEAR ERIS SWAP - CHICAGO BOARD OF TRADE,191119,2019-11-19,344601,CBT,0,344,50735,11499,60,...,82.0,99.7,94.6,37.0,33.9,42.5,40.8,"100,000 USD notional principal",F50,Combined

In [7]:
Market = df.Market_and_Exchange_Names.drop_duplicates()
print(Market)

0            CANADIAN DOLLAR - CHICAGO MERCANTILE EXCHANGE
52               SWISS FRANC - CHICAGO MERCANTILE EXCHANGE
104      BRITISH POUND STERLING - CHICAGO MERCANTILE EX...
156             JAPANESE YEN - CHICAGO MERCANTILE EXCHANGE
208                  EURO FX - CHICAGO MERCANTILE EXCHANGE
                               ...
9959        5 YEAR DELIVERABLE IR - CHICAGO BOARD OF TRADE
10012    5-Year Eris Standard- Initial - ERIS FUTURES E...
10073                BITCOIN - CHICAGO MERCANTILE EXCHANGE
12433          10 YEAR ERIS SWAP  - CHICAGO BOARD OF TRADE
12435            5 YEAR ERIS SWAP - CHICAGO BOARD OF TRADE
Name: Market_and_Exchange_Names, Length: 71, dtype: object

In [50]:
df_a.to_excel('total_a.xlsx')

In [ ]:
NonRept_Positions_Short_Other